name: Fetch AI Repo MD Files

on:
  schedule:
    - cron: '0 0 * * *' # 매일 자정에 실행
  workflow_dispatch: # 수동 실행 옵션

jobs:
  fetch_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo (Artificial-Intelligence)
        uses: actions/checkout@v3
        with:
          repository: SehwanHong/Artificial-Intelligence
          path: temp_ai_repo

      - name: List MD files and create data file
        run: |
          echo "files:" > ai_files.yml
          find temp_ai_repo -maxdepth 1 -name '*.md' -printf "  - name: %f\n    url: https://github.com/SehwanHong/Artificial-Intelligence/blob/main/%f\n" >> ai_files.yml
          cat ai_files.yml

      - name: Checkout current repo (website)
        uses: actions/checkout@v3
        with:
          path: main_website_repo

      - name: Move data file and commit
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }} # GitHub Personal Access Token
        run: |
          mkdir -p main_website_repo/_data
          mv ai_files.yml main_website_repo/_data/ai_repo_files.yml
          cd main_website_repo
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add _data/ai_repo_files.yml
          # 변경 사항이 있을 때만 커밋하도록 수정
          if ! git diff --staged --quiet; then
            git commit -m "Update AI repo MD file list"
            git push
          else
            echo "No changes to commit."
          fi
        working-directory: . # Action의 기본 작업 디렉토리에서 실행 