name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  repository_dispatch:
    types: [ai-repo-updated]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main blog repository
        uses: actions/checkout@v4

      - name: Checkout Artificial-Intelligence repository into collection folder
        uses: actions/checkout@v4
        with:
          repository: SehwanHong/Artificial-Intelligence
          path: _artificial-intelligence

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
          bundler-cache: false

      - name: Install dependencies
        run: bundle install
      
      - name: Build with Jekyll
        run: bundle exec jekyll build --source . --destination _site --trace

      - name: Check build output
        run: ls -R _site
        
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          force_orphan: true 